name: "Build artifact"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-2404
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: [MY_USER]
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and send to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: [MY_USER]/projeto_go:latest,[MY_USER]/projeto_go:${{ github.sha }}
